<?php

/* Generated by tools/scaffold-admin.php. Edit the table there, not this file. */

App::render('admin/layout', [
    'page' => 'analytics',
    'title' => 'Web Analytics',
    'type' => 'plain',
]);
