<?php

/* Generated by tools/scaffold-admin.php. Edit the table there, not this file. */

App::render('admin/layout', [
    'page' => 'blog',
    'title' => 'Write a post',
    'type' => 'editor',
    'script' => 'blog-form',
]);
