<?php

/* Generated by tools/scaffold-admin.php. Edit the table there, not this file. */

App::render('admin/layout', [
    'page' => 'doctors',
    'title' => 'Doctors',
    'type' => 'list',
    'body' => 'admin/body/doctors',
]);
