<?php

/* Generated by tools/scaffold-admin.php. Edit the table there, not this file. */

App::render('admin/layout', [
    'page' => 'doctors',
    'title' => 'Doctor',
    'type' => 'form-static',
    'script' => 'doctor-form',
    'body' => 'admin/body/doctor-form',
]);
