<?php

/* Generated by tools/scaffold-admin.php. Edit the table there, not this file. */

App::render('admin/layout', [
    'page' => 'enquiries',
    'title' => 'Enquiry',
    'type' => 'form',
    'script' => 'enquiry-view',
]);
