<?php

/* Generated by tools/scaffold-admin.php. Edit the table there, not this file. */

App::render('admin/layout', [
    'page' => 'leadership',
    'title' => 'Leadership member',
    'type' => 'form',
    'script' => 'leadership-form',
]);
