<?php

/* Generated by tools/scaffold-admin.php. Edit the table there, not this file. */

App::render('admin/layout', [
    'page' => 'profile',
    'title' => 'My Profile',
    'type' => 'form',
]);
