<?php

/* Generated by tools/scaffold-admin.php. Edit the table there, not this file. */

App::render('admin/layout', [
    'page' => 'settings-theme',
    'title' => 'Theme & Branding',
    'type' => 'form',
]);
